### PR TITLE
bug: [sc-103753] Host analysers are not deduplicating during multiple spec merges #1485

### LINKED ISSUE #1485: Host analysers are not deduplicating during multiple spec merges
**Bug Description**

If I have the same host analyser defined in two different specs they end up showing twice when I run `kubectl support-bundle spec0 spec1`. The same does not happen with a regular analyser, only with host analysers. It seems like the same deduplication applied for analysers is not applied for host analysers.

**Expected Behavior**

My duplicated host analyser to show up only once.

**Steps To Reproduce**

Create two specs with the same host analyser:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: embedded-cluster-host-support-bundle
spec:
  hostCollectors:
  - memory: {}
  hostAnalyzers:
  - memory:
      checkName: Amount of Memory
      outcomes:
      - warn:
          when: "< 2G"
          message: At least 2G of memory is recommended
      - pass:
          message: The system has at least 2G of memory
```

Then run the support-bundle passing both specs:

```
kubectl support-bundle spec0.yaml spec1.yaml
```

With the `--dry-run` flag I can see that the same host analyser is duplicated in the merged result.

### PR DESCRIPTION
**Pull request by nvanthao**
## Description, Motivation and Context

Fixes: https://github.com/replicatedhq/troubleshoot/issues/1485

Given spec `sb.yaml`

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sb
spec:
  analyzers:
  - clusterVersion: {}
  hostCollectors:
  - cpu: {}
  hostAnalyzers:
  - cpu: {}
```

and command

```
support-bundle --interactive=false sb.yaml sb.yaml --dry-run
```

Before

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  creationTimestamp: null
  name: merged-support-bundle-spec
spec:
  analyzers:
  - clusterVersion:
      outcomes: null
  - clusterVersion:
      outcomes: null
  hostAnalyzers:
  - cpu:
      outcomes: null
  - cpu:
      outcomes: null
  hostCollectors:
  - cpu: {}
  - cpu: {}
status: {}

```

After

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  creationTimestamp: null
  name: merged-support-bundle-spec
spec:
  analyzers:
  - clusterVersion:
      outcomes: null
  hostAnalyzers:
  - cpu:
      outcomes: null
  hostCollectors:
  - cpu: {}
status: {}
```

## Checklist

- [X] New and existing tests pass locally with introduced changes.
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [X] Yes
- [ ] No

Duplicated specs with `Analyzer`, `HostCollector` and `HostAnalayzer` will now be merged by their stringified content

### CODE REVIEW

**Comment by xavpaice** [comment]
quick question - how does this interact if there's a url in one of the specs?  Just want to confirm that the dedup happens _after_ the url content replaced that particular spec.

**Comment by nvanthao** [comment]
the dedupe happens after loading URI spec here
https://github.com/replicatedhq/troubleshoot/blob/f7ac39f1cb8eedae250e5cf3f81bdf86c0287172/cmd/troubleshoot/cli/run.go#L297

File: cmd/troubleshoot/cli/run.go [hunk 1]
```diff
@@ -362,6 +362,18 @@ func loadSpecs(ctx context.Context, args []string, client kubernetes.Interface)
 		additionalRedactors.Spec.Redactors = util.Append(additionalRedactors.Spec.Redactors, r.Spec.Redactors)
 	}
 
+	// dedupe specs
+	if len(mainBundle.Spec.Analyzers) > 0 {
```
Comment (DexterYan) [inline cmd/troubleshoot/cli/run.go]: I think we also need remove duplicates in collectors

```
	if len(mainBundle.Spec.Collectors) > 0 {
		mainBundle.Spec.Collectors = collect.DedupCollectors(mainBundle.Spec.Collectors)
	}
```

this sb.yaml will have duplicated collectors
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sb
spec:
  collectors:
  - clusterResources: {}
  analyzers:
  - clusterVersion: {}
  hostCollectors:
  - cpu: {}
  hostAnalyzers:
  - cpu: {}

```

Comment (DexterYan) [reply cmd/troubleshoot/cli/run.go]:
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  creationTimestamp: null
  name: merged-support-bundle-spec
spec:
  analyzers:
  - clusterVersion:
      outcomes: null
  collectors:
  - clusterResources: {}
  - clusterResources: {}
  - clusterInfo: {}
  hostAnalyzers:
  - cpu:
      outcomes: null
  hostCollectors:
  - cpu: {}
status: {}
```

File: pkg/collect/collect.go [hunk 2]
```diff
@@ -192,3 +192,22 @@ func CollectRemote(c *troubleshootv1beta2.RemoteCollector, additionalRedactors *
 	collectResult.AllCollectedData = allCollectedData
 	return collectResult, nil
 }
+
+func DedupHostCollectors(allCollectors []*troubleshootv1beta2.HostCollect) []*troubleshootv1beta2.HostCollect {
```
Comment (banjoh) [inline pkg/collect/collect.go]: I would DRY this code. `DedupHostCollectors` and `DedupHostAnalyzers` are very similar and can be one function. Think go Generics

Comment (nvanthao) [reply pkg/collect/collect.go]: Thanks @banjoh!

The reason I don't why a generic function is that there're existing dedupe functions

https://github.com/replicatedhq/troubleshoot/blob/6b368f22213786d25bf71172d587325c19fbc7ec/pkg/collect/collector.go#L266

https://github.com/replicatedhq/troubleshoot/blob/db871e6889f69856be3084230569d1e558e36613/pkg/analyze/analyzer.go#L261

I think a separate PR is needed to have a generic function and replace others dedupe functions as well.

Comment (banjoh) [reply pkg/collect/collect.go]: I was referring to https://gobyexample.com/generics, but it can be done in another PR

**Review by banjoh — DISMISSED** [review]

File: pkg/collect/collect.go (hunk 2 above)
Comment (banjoh) [reply pkg/collect/collect.go]: Specifically, like so

```go
func Dedup[T any](objs []T) []T {
	seen := make(map[string]bool)
	out := []T{}

	for _, o := range objs {
		data, err := json.Marshal(o)
		if err != nil {
			out = append(out, o)
			continue
		}
		key := string(data)
		if _, ok := seen[key]; !ok {
			out = append(out, o)
			seen[key] = true
		}
	}
	return out
}
```

Then use it like this

```go
func DedupHostCollectors(allCollectors []*troubleshootv1beta2.HostCollect) []*troubleshootv1beta2.HostCollect {
	return utils.Dedup(allCollectors)
}

func DedupHostAnalyzers(allAnalyzers []*troubleshootv1beta2.HostAnalyze) []*troubleshootv1beta2.HostAnalyze {
	return interfaceutils.Dedup(allAnalyzers)
}
```

You probably do not even need `DedupHostAnalyzers` and `DedupHostCollectors`

**Review by DexterYan — CHANGES_REQUESTED** [review]

File: pkg/collect/collect.go (hunk 2 above)
Comment (nvanthao) [reply pkg/collect/collect.go]: many thanks @banjoh! with feedback from @DexterYan  as well on the collector dedup, I have followed our suggestions and updated accordingly.

File: cmd/troubleshoot/cli/run.go (hunk 1 above)
Comment (nvanthao) [reply cmd/troubleshoot/cli/run.go]: thanks @DexterYan I have updated with collector dedup using generic

**Review by banjoh — APPROVED** [review]
Ship it

**Review by DexterYan — APPROVED** [review]
