### PR TITLE
preflight: add yaml output format

### LINKED ISSUE #905: Kubectl preflight --format=yaml results in error that yaml is an unknown output format
**Bug Description**

Running with `kubectl preflight --format=yaml --interactive=false ...`
results in
```
name: cluster-resources    status: running         completed: 0    total: 2
name: cluster-resources    status: completed       completed: 1    total: 2
name: cluster-info         status: running         completed: 1    total: 2
name: cluster-info         status: completed       completed: 2    total: 2
Error: unknown output format: "yaml"
```
**Expected Behavior**
Output should be:
```yaml
pass:
    - title: Required Kubernetes Version
       message: Your cluster meets the recommended and required versions of Kubernetes.
```

**Steps To Reproduce**
Run the preflight plugin with `--format=yaml` worth noting that `--format=json` does work.

**Additional Context**
```
kubectl preflight version
Replicated Preflight 0.49.1
```
MacOS Ventura

### PR DESCRIPTION
**Pull request by CpuID**
## Description, Motivation and Context

`kubectl preflight --format=yaml` returns an error currently, `Error: unknown output format: "yaml"`.

This adds a valid YAML output format.

Fixes: https://github.com/replicatedhq/troubleshoot/issues/905

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by CpuID** [comment]
Below input file is https://raw.githubusercontent.com/replicatedhq/troubleshoot/main/config/samples/troubleshoot_v1beta2_preflight.yaml with `uploadResultsTo` commented out, due to https://github.com/replicatedhq/troubleshoot/pull/939 not being approved/merged as yet (with that PR, this would work with the URL above verbatim)

```
❯ ./preflight --format=yaml --interactive=false --output=/tmp/output ~/troubleshoot905/troubleshoot_v1beta2_preflight.yaml
name: cluster-resources    status: running         completed: 0    total: 2   
name: cluster-resources    status: completed       completed: 1    total: 2   
name: cluster-info         status: running         completed: 1    total: 2   
name: cluster-info         status: completed       completed: 2    total: 2   
pass:
- title: Required Kubernetes Version
  message: The version of Kubernetes you have installed meets the required and recommended
    versions.
fail:
- title: Analyzer Failed
  message: 'failed to get file contents for image pull secrets: File not found: cluster-resources/image-pull-secrets'
- title: Required storage classes
  message: The required storage class was not found in the cluster.
- title: Ingress my-app-ingress
  message: Expected to find an ingress named "my-app-ingress".
- title: Analyzer Failed
  message: invalid analyzer
```

**Review by banjoh — DISMISSED** [review]
LGTM

File: pkg/preflight/stdout_results.go [hunk 1]
```diff
@@ -37,27 +40,29 @@ func showStdoutResultsHuman(preflightName string, analyzeResults []*analyzerunne
...
-		Message string `json:"message"`
-		URI     string `json:"uri,omitempty"`
-		Strict  bool   `json:"strict,omitempty"`
-	}
-	type Output struct {
-		Pass []ResultOutput `json:"pass,omitempty"`
-		Warn []ResultOutput `json:"warn,omitempty"`
-		Fail []ResultOutput `json:"fail,omitempty"`
-	}
+type StdoutResultOutput struct {
```
Comment (banjoh) [inline pkg/preflight/stdout_results.go]: Nit pick: Lower case to make this private. Its not used imported elsewhere

File: pkg/preflight/stdout_results.go [hunk 2]
```diff
@@ -37,27 +40,29 @@ func showStdoutResultsHuman(preflightName string, analyzeResults []*analyzerunne
...
+	Title   string `json:"title" yaml:"title"`
+	Message string `json:"message" yaml:"message"`
+	URI     string `json:"uri,omitempty" yaml:"uri,omitempty"`
+	Strict  bool   `json:"strict,omitempty" yaml:"strict,omitempty"`
+}
+
+type StdoutOutput struct {
```
Comment (banjoh) [inline pkg/preflight/stdout_results.go]: Nit pick: Lower case to make this private. Its not used imported elsewhere

**Review by diamonwiggins — DISMISSED** [review]
lgtm. will hold on merging in lieu of @banjoh's comment

File: pkg/preflight/stdout_results.go (hunk 1 above)
Comment (CpuID) [reply pkg/preflight/stdout_results.go]: good catch, I agree best to make it private, doesn't need to be imported for use elsewhere

I'll adjust this morning 👍

**Review by xavpaice — APPROVED** [review]
