### PR TITLE
feat(analyzer): fix clusterResource analyzer  always uses the first object found

### LINKED ISSUE #1184: `clusterResource` analyzer ignores the `name` property and always uses the first object found
**Bug Description**

Today the analyzer will always return the first result object in the list because the `name` property being provided by the end-user is ignored. This is due to a collision in the variable name used for name of the object being searched for and the actual object in the collected contents.

See - https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/kube_resource.go#L96-L103

**Expected Behavior**

The analyzer should return the unique object expected and not the first result

**Steps To Reproduce**

Using:
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight
spec:
  collectors:
    - clusterResources: {}
  analyzers:
    - clusterResource:
        clusterScoped: false
        checkName: check-pvc
        kind: pvc 
        name: some-pvc
        namespace: default
        yamlPath: "spec.accessModes.[0]"
        expectedValue: ReadWriteOnce
        outcomes:
          - fail:
              when: "false"
              message: isFalse
          - pass:
              when: "true"
              message: isTrue
```

Even if `some-pvc` doesn't exist, as long as at least one PVC exists in the `default` namespace, and that PVC had an accessMode of `ReadWriteOnce` the analyzer would pass.

### PR DESCRIPTION
**Pull request by DexterYan**
## Description, Motivation and Context

- fix a variable name collision
- update tests to test no existed resource

Fixes: #1184

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: pkg/analyze/kube_resource_test.go [hunk 1]
```diff
@@ -24,22 +26,34 @@ func Test_clusterResource(t *testing.T) {
...
+			resourceExists: true,
 			analyzer: troubleshootv1beta2.ClusterResource{
 				CollectorName: "Check namespaced resource",
 				Kind:          "Node",
 				ClusterScoped: true,
 				Name:          "repldev-marc",
 			},
 		},
+		{
+			name:           "not existed resource",
```
Comment (xavpaice) [inline pkg/analyze/kube_resource_test.go]:
```suggestion
			name:           "resource does not exist",
```

File: pkg/analyze/kube_resource_test.go [hunk 2]
```diff
@@ -24,22 +26,34 @@ func Test_clusterResource(t *testing.T) {
...
+			resourceExists: false,
+			analyzer: troubleshootv1beta2.ClusterResource{
+				CollectorName: "Check namespaced resource",
+				Kind:          "Node",
+				ClusterScoped: true,
+				Name:          "not-existed-resource",
```
Comment (xavpaice) [inline pkg/analyze/kube_resource_test.go]:
```suggestion
				Name:          "resource-does-not-exist",
```

**Review by xavpaice — CHANGES_REQUESTED** [review]
Couple of very minor suggestions, otherwise LGTM.

**Review by xavpaice — APPROVED** [review]
