### PR TITLE
call out to `fio` for host filesystem performance

### LINKED ISSUE #1215: filesystemPerformance check false alarms
**Bug Description**

When running HostPreflight checks, the filesystemPerformance check returns a warning for disk latency on an instance that appears to be fine if we ignore the warning.

**Expected Behavior**

Do not warn unless there's a genuine performance issue.

**Steps To Reproduce**

Instance types:
* AWS EC2 us-west-2 m5.4xlarge with EBS block store
* t3.xlarge and a gp2 volume

Measured results with the collector in https://github.com/replicatedhq/kURL/blob/e17edc5d2971fda3f0a1f168cae7aa6ce8e7b5df/pkg/preflight/assets/host-preflights.yaml#L512-L513:

```
[WARN] Filesystem Performance: Write latency is high. p99 target < 10ms, actual:
   Min: 1.249011ms
   Max: 219.425382ms
   Avg: 3.64555ms
    p1: 1.408942ms
    p5: 1.526009ms
   p10: 1.602084ms
   p20: 1.709857ms
   p30: 1.798301ms
   p40: 1.884261ms
   p50: 1.976585ms
   p60: 2.074297ms
   p70: 2.193705ms
   p80: 2.370422ms
   p90: 2.740913ms
   p95: 3.383787ms
   p99: 66.95246ms
 p99.5: 85.128422ms
 p99.9: 140.532147ms
p99.95: 155.877727ms
p99.99: 185.874478ms
```

**Additional Context**

This is potentially an issue with the warm up time, which currently defaults to 10s. 

Things to try:
* run the test 3-4 times in a row, with no gap between - and compare the results
* increase the warmup to 30s or more
* compare the results from the collector against fio, and other similar common tools

### PR DESCRIPTION
**Pull request by adamancini**
## Description, Motivation and Context

Shell out to the `fio` utility to collect filesystem write latency info instead of using the old method of writing to disk directly.  Work in some additional types to support using any of the metrics that `fio` returns in future analyzers.

#1215 

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [x] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)
https://github.com/replicatedhq/troubleshoot.sh/pull/519

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

the collector will require the installation of the `fio` binary.  If `fio` is not installed, the collector will fail to run and print an error, similarly to our other collectors that require userspace utilities to be installed.

### CODE REVIEW

File: bin/watch.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
+#!/usr/bin/env node
```
Comment (banjoh) [inline bin/watch.js]: I'm assuming you intended to rename https://github.com/replicatedhq/troubleshoot/blob/main/bin/watchrsync.js?

Comment (adamancini) [reply bin/watch.js]: forgot to remove it from the PR

**Comment by xavpaice** [comment]
can we get a description in the PR for what this is doing exactly, and fix up the merge conflicts?  I'm hoping that'll trigger the tests to run.

We are going to need to get some testing into this PR to be able to approve it.

I like the approach, makes sense to me and will produce much more accurate results.

**Comment by adamancini** [comment]
ok, tests should finally run, fixed up go.mod problems, @xavpaice ack on the test coverage

**Comment by adamancini** [comment]
https://github.com/replicatedhq/troubleshoot.sh/pull/519 docs

**Comment by danj-replicated** [comment]
running this without sudo causes a panic
```
2023/08/25 15:08:51 open /var/lib/etcd/fsperf: permission denied
panic: open /var/lib/etcd/fsperf: permission denied [recovered]
	panic: open /var/lib/etcd/fsperf: permission denied
```

would be good if we could test access first and throw a human readable error about the necessity of elevating permissions

**Comment by adamancini** [comment]
added some code to handle permission errors gracefully:

```
ada@ada-kurl:~$ ./support-bundle sample-troubleshoot.yaml

 * failed to run host collector: filesystem-latency-two-minute-benchmark-background-iops-off: open /var/lib/etcd/fsperf permission denied.  Please run this collector as root.: open /var/lib/etcd/fsperf: permission denied


support-bundle-2023-09-06T20_09_26.tar.gz
```

File: pkg/collect/host_filesystem_performance_linux.go [hunk 2]
```diff
@@ -38,6 +47,45 @@ func (d Durations) Swap(i, j int) {
...
 }
 
+func collectFioResults(opts FioJobOptions) (*FioResult, error) {
+
+	command := []string{"fio"}
+	v := reflect.ValueOf(opts)
+	t := reflect.TypeOf(opts)
+	for i := 0; i < v.NumField(); i++ {
+		field := t.Field(i)
+		value := v.Field(i)
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_linux.go]: You want to check for the zero value and ignore adding the field to the CLI, else you will end up with `fio --name=fsperf --bs= --directory=/home/evans`. Note the `--bs` flag

```go
if !value.IsZero() {
	command = ...
}
```

This is probably a minor thing cause the parameters are hardcoded [here](https://github.com/adamancini/troubleshoot/blob/107806052302281a31e38ea20a803af13d721c23/pkg/collect/host_filesystem_performance_linux.go#L190) but best to be safe

File: pkg/collect/host_filesystem_performance.go [hunk 3]
```diff
@@ -90,3 +91,234 @@ func (f FSPerfResults) String() string {
...
+	P90   int `json:"90.000000,omitempty"`
+	P95   int `json:"95.000000,omitempty"`
+	P99   int `json:"99.000000,omitempty"`
+	P995  int `json:"99.500000,omitempty"`
+	P999  int `json:"99.900000,omitempty"`
+	P9995 int `json:"99.950000,omitempty"`
+	P9999 int `json:"99.990000,omitempty"`
+}
+
+func (d FioDiskUtil) Print() string {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: Change this to `func (d FioDiskUtil) String() string {`. Its Go's standard way of "stringifying" an object. Once you make that change, any string formatting will detect the new `String()` method i.e `fmt.Sprintf("%s\n", object)`

**Review by banjoh — COMMENTED** [review]
Changes look good. I ran some tests using both `preflight` and `support-bundle` binaries.

I made a few minor comments to improve the code

File: pkg/collect/host_filesystem_performance.go (hunk 3 above)
Comment (adamancini) [reply pkg/collect/host_filesystem_performance.go]: @banjoh ty!

File: pkg/collect/host_filesystem_performance.go [hunk 4]
```diff
@@ -90,3 +91,234 @@ func (f FSPerfResults) String() string {
...
+	FioVersion    string           `json:"fio version,omitempty"`
+	Timestamp     int64            `json:"timestamp,omitempty"`
+	TimestampMS   int64            `json:"timestamp_ms,omitempty"`
+	Time          string           `json:"time,omitempty"`
+	GlobalOptions FioGlobalOptions `json:"global options,omitempty"`
+	Jobs          []FioJobs        `json:"jobs,omitempty"`
+	DiskUtil      []FioDiskUtil    `json:"disk_util,omitempty"`
+}
+
+func (f FioResult) Print() string {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: One more change to `String()`

File: pkg/collect/host_filesystem_performance.go [hunk 5]
```diff
@@ -90,3 +91,234 @@ func (f FSPerfResults) String() string {
...
+type FioGlobalOptions struct {
+	Directory  string `json:"directory,omitempty"`
+	RandRepeat string `json:"randrepeat,omitempty"`
+	Verify     string `json:"verify,omitempty"`
+	IOEngine   string `json:"ioengine,omitempty"`
+	Direct     string `json:"direct,omitempty"`
+	GtodReduce string `json:"gtod_reduce,omitempty"`
+}
+
+func (g FioGlobalOptions) Print() string {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: One more change to `String()`

File: pkg/collect/host_filesystem_performance.go [hunk 6]
```diff
@@ -90,3 +91,234 @@ func (f FSPerfResults) String() string {
...
+	LatencyNs         FioLatency    `json:"latency_ns,omitempty"`
+	LatencyUs         FioLatency    `json:"latency_us,omitempty"`
+	LatencyMs         FioLatency    `json:"latency_ms,omitempty"`
+	LatencyDepth      int32         `json:"latency_depth,omitempty"`
+	LatencyTarget     int32         `json:"latency_target,omitempty"`
+	LatencyPercentile float32       `json:"latency_percentile,omitempty"`
+	LatencyWindow     int32         `json:"latency_window,omitempty"`
+}
+
+func (j FioJobs) Print() string {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: One more change to `String()`

File: pkg/collect/host_filesystem_performance.go [hunk 7]
```diff
@@ -90,3 +91,234 @@ func (f FSPerfResults) String() string {
...
+	BS        string `json:"bs,omitempty"`
+	Directory string `json:"directory,omitempty"`
+	RW        string `json:"rw,omitempty"`
+	IOEngine  string `json:"ioengine,omitempty"`
+	FDataSync string `json:"fdatasync,omitempty"`
+	Size      string `json:"size,omitempty"`
+	RunTime   string `json:"runtime,omitempty"`
+}
+
+func (o FioJobOptions) Print() string {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: One more change to `String()`

File: pkg/collect/host_filesystem_performance.go [hunk 8]
```diff
@@ -90,3 +91,234 @@ func (f FSPerfResults) String() string {
...
+	BwDev       float32       `json:"bw_dev,omitempty"`
+	BwSamples   int32         `json:"bw_samples,omitempty"`
+	IopsMin     int32         `json:"iops_min,omitempty"`
+	IopsMax     int32         `json:"iops_max,omitempty"`
+	IopsMean    float32       `json:"iops_mean,omitempty"`
+	IopsStdDev  float32       `json:"iops_stddev,omitempty"`
+	IopsSamples int32         `json:"iops_samples,omitempty"`
+}
+
+func (s FioStats) Print() string {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: One more change to `String()`

**Comment by adamancini** [comment]
~merged main, updated collector tests, ready for re-re-review~

mm tests are failing, have to fix something

File: pkg/collect/host_filesystem_performance.go [hunk 9]
```diff
@@ -2,17 +2,25 @@ package collect
...
+	"github.com/pkg/errors"
 	troubleshootv1beta2 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta2"
+	"k8s.io/apimachinery/pkg/api/resource"
+	"k8s.io/klog/v2"
 )
 
-func init() {
-	rand.Seed(time.Now().UnixNano())
-}
+// func init() {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: Lets just remove the code if its not needed

File: pkg/collect/host_filesystem_performance_linux.go [hunk 10]
```diff
@@ -50,46 +50,36 @@ func collectHostFilesystemPerformance(hostCollector *troubleshootv1beta2.Filesys
...
-	}
-	defer func() {
-		if err := f.Close(); err != nil {
-			log.Println(err.Error())
-		}
-		if err := os.Remove(filename); err != nil {
-			log.Println(err.Error())
-		}
-	}()
+	// filename := filepath.Join(hostCollector.Directory, fioJobOptions.Name)
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_linux.go]: I'm assuming this code is no longer needed cause `fio` command will test if the directory is writable, right?

Lets remove the code instead of commenting it out

File: pkg/collect/host_filesystem_performance_test.go [hunk 11]
```diff
@@ -57,3 +60,130 @@ func TestGetPercentileIndex(t *testing.T) {
...
+			wantOptions: nil,
+			wantErr:     true,
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			gotCommand, gotOptions, err := parseCollectorOptions(tt.args.hostCollector)
+			if (err != nil) != tt.wantErr {
+				t.Errorf("parseCollectorOptions() error = %v, wantErr %v", err, tt.wantErr)
+				return
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_test.go]: Nit: Unnecessary
```suggestion
```

File: pkg/collect/host_filesystem_performance_test.go [hunk 12]
```diff
@@ -57,3 +60,130 @@ func TestGetPercentileIndex(t *testing.T) {
...
+			} else {
+				if !reflect.DeepEqual(gotCommand, tt.wantCommand) {
+					t.Errorf("parseCollectorOptions() got command = %v, want %v", gotCommand, tt.wantCommand)
+				}
+				if !reflect.DeepEqual(gotOptions, tt.wantOptions) {
+					t.Errorf("parseCollectorOptions() got options = %v, want %v", gotOptions, tt.wantOptions)
+				}
+				return
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_test.go]:
```suggestion
```

File: pkg/collect/host_filesystem_performance_linux.go [hunk 13]
```diff
@@ -50,46 +50,36 @@ func collectHostFilesystemPerformance(hostCollector *troubleshootv1beta2.Filesys
...
+	// 	if err := f.Close(); err != nil {
+	// 		log.Println(err.Error())
+	// 	}
+	// 	if err := os.Remove(filename); err != nil {
+	// 		log.Println(err.Error())
+	// 	}
+	// }()
 
 	// Start the background IOPS task and wait for warmup
 	if hostCollector.EnableBackgroundIOPS {
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_linux.go:50]: How does `fio` work when we [enable background iops](https://troubleshoot.sh/docs/host-collect-analyze/filesystemPerformance/#enablebackgroundiops-optional)? How are these two features meant to work together? Does `fio` have an equivalent capability?

File: pkg/collect/host_filesystem_performance.go [hunk 14]
```diff
@@ -90,3 +98,324 @@ func (f FSPerfResults) String() string {
...
+func collectFioResults(hostCollector *troubleshootv1beta2.FilesystemPerformance) (*FioResult, error) {
+
+	command, opts, err := parseCollectorOptions(hostCollector)
+
+	if err != nil {
+		return nil, errors.Wrap(err, "failed to parse collector options")
+	}
+
+	klog.V(2).Infof("collecting fio results: %s", strings.Join(command, " "))
+	output, err := exec.Command(command[0], command[1:]...).Output()
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance.go]: Lets use `exec.CommandContext` command so that we can respect the collector's [timeout](https://troubleshoot.sh/docs/host-collect-analyze/filesystemPerformance/#timeout-required). You'll end up having something like below after having passed in the context to `collectFioResults()` which is created in [here](https://github.com/replicatedhq/troubleshoot/blob/fd29012624ad8167ec87b16108407048ae38484d/pkg/collect/host_filesystem_performance_linux.go#L50)

```go
output, err := exec.CommandContext(ctx, command[0], command[1:]...).Output()
```

File: pkg/collect/host_filesystem_performance_test.go [hunk 15]
```diff
@@ -57,3 +60,130 @@ func TestGetPercentileIndex(t *testing.T) {
...
+			},
+			wantOptions: &FioJobOptions{
+				RW:        "write",
+				IOEngine:  "sync",
+				FDataSync: "1",
+				Directory: "/var/lib/etcd",
+				Size:      "23068672",
+				BS:        "1024",
+				Name:      "fsperf",
+				RunTime:   "120",
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_test.go:116]: I'm guessing we are happy with `120s` maximum runtime, right?

**Review by banjoh — COMMENTED** [review]
Changes look good overall. I added a few comments, but nothing that would affect the structure of the PR too much.

File: pkg/collect/host_filesystem_performance_linux.go (hunk 13 above)
Comment (adamancini) [reply pkg/collect/host_filesystem_performance_linux.go:50]: When we enable background IOPS, troubleshoot just performs some additional I/O in the background - we choose the fio parameters to simulate the kind of reads/writes that etcd would perform, but on a fresh VM there's no contention, so we default to enable background IOPS to put some additional IO in the system to simulate that etcd et al. are already running,

File: pkg/collect/host_filesystem_performance_test.go (hunk 15 above)
Comment (adamancini) [reply pkg/collect/host_filesystem_performance_test.go:116]: @banjoh it keeps the same max time as the previous implementation, I'm OK with it.  `fio` usually finishes in less time than that, but allows for a max runtime of 2 minutes.

File: pkg/collect/host_filesystem_performance.go (hunk 9 above)
Comment (adamancini) [reply pkg/collect/host_filesystem_performance.go]: done

**Review by banjoh — DISMISSED** [review]
Ship it :rocket:

File: pkg/collect/host_filesystem_performance_linux.go (hunk 10 above)
Comment (banjoh) [reply pkg/collect/host_filesystem_performance_linux.go:49]: @adamancini were we to clean this up?

File: pkg/collect/host_filesystem_performance_linux.go [hunk 16]
```diff
@@ -50,46 +36,36 @@ func collectHostFilesystemPerformance(hostCollector *troubleshootv1beta2.Filesys
...
-	defer func() {
-		if err := f.Close(); err != nil {
-			log.Println(err.Error())
-		}
-		if err := os.Remove(filename); err != nil {
-			log.Println(err.Error())
-		}
-	}()
+	// filename := filepath.Join(hostCollector.Directory, fioJobOptions.Name)
+	// // Create file handle
```
Comment (banjoh) [inline pkg/collect/host_filesystem_performance_linux.go]: @adamancini were we to clean this up?

Comment (adamancini) [reply pkg/collect/host_filesystem_performance_linux.go]: I thought I had removed this before pushing the last commit 😠

**Review by banjoh — APPROVED** [review]
