### PR TITLE
fix: complete mssql analyser implementation

### LINKED ISSUE #1289: Mssql analyser not working as intended
**Bug Description**

When running the preflight binary, the `mssql` analyser is not analysing data collected data

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - mssql:
        collectorName: mssql
        uri: sqlserver://username:password@hostname:1433/defaultdb
  analyzers:
    - mssql:
        checkName: Must be SQLServer 15.x or later
        collectorName: mssql
        outcomes:
          - fail:
              when: "connected == false"
              message: Cannot connect to SQLServer
          - fail:
              when: "version < 15.x"
              message: The SQLServer must be at least version 15
          - pass:
              message: The SQLServer connection checks out
```

image

**Expected Behavior**

The analyser should fail with `Cannot connect to SQLServer` message

Include a description of the expected behaviour here.

**Steps To Reproduce**

Run `preflight spec.yaml` where the spec contains the yaml above

Include the following information.
- Troubleshoot version: `v0.70.2`

### PR DESCRIPTION
**Pull request by banjoh**
## Description, Motivation and Context

Add missing mssql analyser implementation

Fixes: #1289 

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by danj-replicated — DISMISSED** [review]
lgtm 👍

File: pkg/collect/mssql.go [hunk 1]
```diff
@@ -36,14 +38,25 @@ func (c *CollectMssql) IsExcluded() (bool, error) {
...
+	connUrl, err := url.Parse(c.Collector.URI)
+	// Parsing the uri should not lead to the collector failing
+	// sql.Open will fail if the uri is invalid.
+	if err == nil {
+		klog.V(2).Infof("Connect to %q MSSQL Database", connUrl.Host)
+	} else {
+		klog.V(2).Info("Connect to MSSQL Database")
+	}
+
 	db, err := sql.Open("mssql", c.Collector.URI)
```
Comment (DexterYan) [inline pkg/collect/mssql.go:50]: Looks like after we open the db connection, then there is no `db.Close()` afterward. Should we add one to make sure it closed after we got row.Scan result.

**Review by DexterYan — APPROVED** [review]

**Review by xavpaice — APPROVED** [review]
