### PR TITLE
Handle k8s api deprecations

### LINKED ISSUE #426: Handle k8s api deprecations
**Bug Description**

Running preflight or support-bundle against a recent k8s version produces deprecation warnings, and in k8s v1.22, some k8s object kinds can't be collected.

On k8s `v1.20.0`:
```
./support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot/master/examples/support-bundle/sample-supportbundle.yaml

 Collecting support bundle ⠴ cluster-resourcesW0923 10:18:09.626673  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.628640  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.629498  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.630310  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.631151  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.632010  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.632823  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.633769  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0923 10:18:09.634910  493696 warnings.go:70] storage.k8s.io/v1beta1 StorageClass is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 StorageClass
W0923 10:18:09.640855  493696 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
support-bundle-2021-09-23T10_18_06.tar.gz
```

**Expected Behavior**

There should be no warnings and all requested k8s objects should be collected, irrespective of the k8s version (unless on a k8s version no longer supported by troubleshoot).

**Steps To Reproduce**

Set kubeconfig to k8s >1.20 cluster.

```
kubectl preflight https://raw.githubusercontent.com/replicatedhq/troubleshoot/master/examples/preflight/sample-preflight.yaml
kubectl support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot/master/examples/support-bundle/sample-supportbundle.yaml
```

**Additional Context**

Tested on `v0.13.10` with k8s `v1.20.0`.

**Possible Fix**

Rather than check for specific k8s versions, introduce a check that can determine whether a GVK exists in the cluster.  For collectors that have multiple possibilities, check they exist, from most recent GVK first.  e.g.

```golang
package discovery

import (
	"k8s.io/client-go/discovery"
)

// HasResource takes an api version and a kind of a resource and checks if the resource
// is supported by the k8s api server.
func HasResource(dc discovery.DiscoveryInterface, apiVersion, kind string) (bool, error) {
	_, apiLists, err := dc.ServerGroupsAndResources()
	if err != nil {
		return false, err
	}
	// Compare the resource api version and kind and find the resource.
	for _, apiList := range apiLists {
		if apiList.GroupVersion == apiVersion {
			for _, r := range apiList.APIResources {
				if r.Kind == kind {
					return true, nil
				}
			}
		}
	}
	return false, nil
}
```

For the ingress collector in `pkg/collect/cluster_resources.go`:

```golang
func ingress(ctx context.Context, client *kubernetes.Clientset, namespaces []string) (map[string][]byte, map[string]string) {
	ok, err := discovery.HasResource(client, "networking.k8s.io/v1", "Ingress")
	if err != nil {
		return nil, map[string]string{"": err.Error()}
	}
	if ok {
		return ingressv1(ctx, client, namespaces)
	}

	return ingressv1beta(ctx, client, namespaces)
}
```

I'm happy to work on this or an alternative.

### PR DESCRIPTION
**Pull request by croomes**
Introduces a mechanism to verify whether the k8s server supports a given GVK.

Uses v1 API implementations if they exist for Ingress, StorageClass and CustomResourceDefinition, and current behaviour (v1beta1) if they don't.  This avoids deprecation warnings such as:

```
W0923 10:18:09.628640  493696 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

Fixes #426

### CODE REVIEW

File: pkg/k8sutil/discovery/discovery_test.go [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+		tc := tc
+		t.Run(tc.name, func(t *testing.T) {
+			client := fakeclientset.NewSimpleClientset()
+			fakeDiscovery, ok := client.Discovery().(*fakediscovery.FakeDiscovery)
+			if !ok {
+				t.Fatalf("could not convert Discovery() to *FakeDiscovery")
+			}
+			fakeDiscovery.Resources = tc.apiResourceList
+
+			exists, err := HasResource(fakeDiscovery, testKindGroupVersion, testKind)
```
Comment (laverya) [inline pkg/k8sutil/discovery/discovery_test.go:71]: Should `testKindGroupVersion` and `testKind` be parameterized within the test case instead of static for all test cases?

**Review by laverya — APPROVED** [review]

**Review by emosbaugh — APPROVED** [review]
LGTM! Thanks again for the contribution
