### PR TITLE
fix(json_compare): solve unorderd slice deep equal

### LINKED ISSUE #1274: Intermittent test failures with jsonpath_comparison,_multiple_values
**Bug Description**

During test runs, we see intermittent failures reporting:

```
=== RUN   Test_jsonCompare/jsonpath_comparison,_multiple_values
    json_compare_test.go:699: 
        	Error Trace:	/home/runner/work/troubleshoot/troubleshoot/pkg/analyze/json_compare_test.go:699
        	Error:      	Not equal: 
        	            	expected: analyzer.AnalyzeResult{IsPass:true, IsFail:false, IsWarn:false, Strict:false, Title:"jsonpath-compare-2", Message:"pass", URI:"", IconKey:"kubernetes_text_analyze", IconURI:"https://troubleshoot.sh/images/analyzer-icons/text-analyze.svg", InvolvedObject:(*v1.ObjectReference)(nil)}
        	            	actual  : analyzer.AnalyzeResult{IsPass:false, IsFail:true, IsWarn:false, Strict:false, Title:"jsonpath-compare-2", Message:"fail", URI:"", IconKey:"kubernetes_text_analyze", IconURI:"https://troubleshoot.sh/images/analyzer-icons/text-analyze.svg", InvolvedObject:(*v1.ObjectReference)(nil)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 (analyzer.AnalyzeResult) {
        	            	- IsPass: (bool) true,
        	            	- IsFail: (bool) false,
        	            	+ IsPass: (bool) false,
        	            	+ IsFail: (bool) true,
        	            	  IsWarn: (bool) false,
        	            	@@ -6,3 +6,3 @@
        	            	  Title: (string) (len=18) "jsonpath-compare-2",
        	            	- Message: (string) (len=4) "pass",
        	            	+ Message: (string) (len=4) "fail",
        	            	  URI: (string) "",
        	Test:       	Test_jsonCompare/jsonpath_comparison,_multiple_values
--- FAIL: Test_jsonCompare (0.00s)
```

This test appears to be performing a recursive search using jsonpath and `JsonPath:      "{$..bar}",`.  The result returned is expected to be ```Value: `[true, 123]`,``` however in some runs, that's not the case.

**Expected Behavior**

Tests pass consistently.

**Steps To Reproduce**

Run unit tests often.

**Additional Context**

### PR DESCRIPTION
**Pull request by DexterYan**
## Description, Motivation and Context

- sort slices first, then use reflect.DeepEqual to compare
- compares two slices of interfaces and returns true if they contain the same values

Fixes: #1274
## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: pkg/analyze/json_compare.go [hunk 1]
```diff
@@ -159,3 +161,58 @@ func (a *AnalyzeJsonCompare) analyzeJsonCompare(analyzer *troubleshootv1beta2.Js
 		Message: "Invalid analyzer",
 	}, nil
 }
+
```
Comment (danj-replicated) [inline pkg/analyze/json_compare.go:165]: I know this is a fairly simple function but it's name is a little confusing. can we get a brief description here to help any future readers grok what's happening.

**Review by danj-replicated — CHANGES_REQUESTED** [review]

File: pkg/analyze/json_compare.go (hunk 1 above)
Comment (DexterYan) [reply pkg/analyze/json_compare.go:165]: Thank you @danj-replicated. Good idea! I have updated the pr to make it more readable and a description for a better understanding.

**Review by danj-replicated — APPROVED** [review]

**Review by banjoh — APPROVED** [review]
