### PR TITLE
fix(flag): fix wrong output filename

### LINKED ISSUE #825: RFE: meaningful default name to save the preflights checks
**Describe the rationale for the suggested feature.**

After run `kubectl preflight https://preflight.replicated.com` and choose the s option to save the default output seems to be "o". Could we change that for for example preflight_checks.txt or  preflight_checks_<timestamp>.txt? 

Screenshot 2022-11-07 at 10 39 23

### PR DESCRIPTION
**Pull request by DexterYan**
## Description, Motivation and Context
- fix the issue of  default output to be "o"
- add go test for flag

Fixes: #825

## Checklist

- [x] New and existing tests pass locally with the changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: pkg/preflight/flags_test.go [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+			AddFlags(&f)
+
+			if err := f.Parse(tt.args); err != nil {
+				if (err != nil) != tt.wantErr {
+					t.Errorf("AddFlags() error = %v, wantErr %v", err, tt.wantErr)
+				}
+			} else {
+				for i, flag := range tt.flags {
+					got, err := f.GetString(flag)
+					if (err != nil) != tt.wantErr {
```
Comment (banjoh) [inline pkg/preflight/flags_test.go]: This is OK, but I like testify's interface better. This would look something like

```go
assert.Equalf(t, (err == nil), tt.wantErr, "AddFlags() error = %v, wantErr %v", err, tt.wantErr)
```

File: pkg/preflight/flags_test.go [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+						t.Errorf("AddFlags() error = %v, wantErr %v", err, tt.wantErr)
+					}
+
+					if got != tt.want[i] {
+						t.Errorf("AddFlags() = %v, want %v", got, tt.want[i])
```
Comment (banjoh) [inline pkg/preflight/flags_test.go]: testify me please :)

File: pkg/preflight/flags_test.go [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+			resetFlags()
+			f := flag.FlagSet{}
+			AddFlags(&f)
+
+			if err := f.Parse(tt.args); err != nil {
+				if (err != nil) != tt.wantErr {
+					t.Errorf("AddFlags() error = %v, wantErr %v", err, tt.wantErr)
+				}
+			} else {
+				for i, flag := range tt.flags {
```
Comment (banjoh) [inline pkg/preflight/flags_test.go]: I would do away with this for loop to simplify the test implementation by having `args`, `flags` and `want` as strings rather than slices. Our test inputs have one value each

File: pkg/preflight/flags_test.go [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+		wantErr: false,
+	}}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			resetFlags()
+			f := flag.FlagSet{}
+			AddFlags(&f)
+
+			if err := f.Parse(tt.args); err != nil {
```
Comment (banjoh) [inline pkg/preflight/flags_test.go]: Minor comment: Perhaps this test is unnecessary. We are testing cobra's ability to parse commands. Unless your intention is to ensure cobra does not break its interface in the future, in which case the required test coverage would be much more than this :)

File: pkg/preflight/flags_test.go [hunk 5]
```diff
@@ -0,0 +1,109 @@
+package preflight
```
Comment (banjoh) [inline pkg/preflight/flags_test.go:1]: Big +1 on adding unit tests

File: pkg/preflight/flags_test.go (hunk 1 above)
Comment (DexterYan) [reply pkg/preflight/flags_test.go]: migrated into
```
assert.Equalf(t, (err != nil), tt.wantErr, "AddFlags() error = %v, wantErr %v", err, tt.wantErr)
```

File: pkg/preflight/flags_test.go (hunk 2 above)
Comment (DexterYan) [reply pkg/preflight/flags_test.go]: migrated to 
```
assert.Equalf(t, got, tt.want, "AddFlags() = %v, wantErr %v", got, tt.want)
```

File: pkg/preflight/flags_test.go (hunk 3 above)
Comment (DexterYan) [reply pkg/preflight/flags_test.go]: good point, I removed slices.

File: pkg/preflight/flags_test.go (hunk 4 above)
Comment (DexterYan) [reply pkg/preflight/flags_test.go]: Really good point! I have restructured the tests. My intention is about to check the add flags and default flag value. It does not need to use the cobra parse function. Thank you for pointing it out.

**Review by banjoh — DISMISSED** [review]

**Comment by banjoh** [comment]
You might want to squash your commits before merging.

**Comment by chris-sanders** [comment]
> You might want to squash your commits before merging.

I believe it's actually required on the repo before merge.

**Comment by DexterYan** [comment]
> > You might want to squash your commits before merging.
> 
> I believe it's actually required on the repo before merge.

Thank you for reminder. I have enabled squash and merge automatically.

**Review by xavpaice — APPROVED** [review]
