### PR TITLE
fix(collectors): Fix logs collection in longhorn collector

### LINKED ISSUE #879: Longhorn collector pod logs not symlinked correctly
**Bug Description**

The pog logs gathered in by the Longhorn collector are not symlinked properly and are instead duplicated within the resultant bundle in a separate `cluster-resources` subdirectory.

Both the following exist
```
./longhorn/longhorn-system/logs/csi-attacher-6795cb849c-9jgdh
./longhorn/longhorn-system/logs/cluster-resources/pods/logs/longhorn-system/csi-attacher-6795cb849c-9jgdh
```

**Expected Behavior**

```
./longhorn/longhorn-system/logs/csi-attacher-6795cb849c-9jgdh
```

Should be a symlink to

```
./cluster-resources/pods/logs/longhorn-system/csi-attacher-6795cb849c-9jgdh
```

**Steps To Reproduce**

Generate a Support Bundle with the latest Troubleshoot Version 

**Additional Context**

Include the following information.
- Troubleshoot version v0.48.1+

### PR DESCRIPTION
**Pull request by banjoh**
## Description, Motivation and Context

When the `longhorn` collector runs, it uses the `logs` collector to collect all the longhorn pod logs. Previously, all the logs would be stored in the `longhorn/longhorn-system/logs` directory of the bundle path after being copied from where the `logs` collector would store them. After [this recent change](https://github.com/replicatedhq/troubleshoot/pull/821), symlinks to logs stored in the `cluster-resources` directory were introduced. This led to the collector including `/cluster-resources/pods/logs/longhorn-system` directory when copying logs which led to a duplicate `cluster-resources` directory in the support bundle. This caused problems when [sbctl tried to discover cluster resources](https://github.com/replicatedhq/sbctl/blob/b525dacc98c1b7e44d5a002d614ae9cd6abace15/pkg/sbctl/support-bundle.go#L74).

This PR ensures the longhorn log files (symlinks) are correctly in `longhorn/longhorn-system/logs` directory of the support bundle.

image

Fixes: #879

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [x] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: pkg/collect/longhorn.go [hunk 1]
```diff
@@ -307,6 +289,29 @@ func (c *CollectLonghorn) Collect(progressChan chan<- interface{}) (CollectorRes
 	return output, nil
 }
 
+func (c *CollectLonghorn) collectLonghornLogs(namespace string, results CollectorResult, progressChan chan<- interface{}, ) error {
+		// logs of all pods in namespace
+		logsCollectorSpec := &troubleshootv1beta2.Logs{
+			Selector:  []string{""},
+			Name:      GetLonghornLogsDirectory(namespace), // Logs (symlinks) will be stored in this directory
```
Comment (banjoh) [inline pkg/collect/longhorn.go]: This it where the fix is

We tell the logs collector to store logs where longhorn expects them. No need of trying to copy files from some other directory using `copyResult()`

Comment (diamonwiggins) [reply pkg/collect/longhorn.go]: will this impact at all where the Longhorn Analyzer is looking for the collected files?

Comment (banjoh) [reply pkg/collect/longhorn.go]: > 

Good question. Analysers will follow symlinks when reading results

Here is an analysis result

image

**Review by diamonwiggins — APPROVED** [review]
