### PR TITLE
preflight: ensure --output produces an output file of the desired format

### LINKED ISSUE #906: Kubectl preflight --output=file doesn't send output to file
**Bug Description**
running `kubectl preflight --format=json --interactive=false --output=/tmp/output` does not result in the file /tmp/output being created with the output.

**Expected Behavior**

`/tmp/output` has the output from the preflight run

**Steps To Reproduce**
run:
`kubectl preflight --format=json --interactive=false --output=/tmp/output` 
notice /tmp/output is not created

**Additional Context**
```
kubectl preflight version
Replicated Preflight 0.49.1
```
MacOS Ventura

### PR DESCRIPTION
**Pull request by CpuID**
## Description, Motivation and Context

preflight: ensure --output produces an output file of the desired format

fixes https://github.com/replicatedhq/troubleshoot/issues/906

tests for this are in https://github.com/replicatedhq/troubleshoot/pull/949 - which fail on `main` (TDD), and pass with this branch included 👍 

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
  - Tests are in https://github.com/replicatedhq/troubleshoot/pull/949
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by CpuID** [comment]
Ran the commits in this branch combined with the tests in https://github.com/replicatedhq/troubleshoot/pull/949 in a throwaway branch...

They pass locally :)

```
~/git/replicatedhq/troubleshoot/pkg/preflight cpuid-906-with-tests *5 !1 ?1 ❯ go test -v -tags integration -run TestRunPreflights                                             28s 20:43:46
=== RUN   TestRunPreflights
=== PAUSE TestRunPreflights
=== CONT  TestRunPreflights
=== RUN   TestRunPreflights/noninteractive-stdout-human
=== RUN   TestRunPreflights/noninteractive-stdout-json
=== RUN   TestRunPreflights/noninteractive-stdout-yaml
=== RUN   TestRunPreflights/noninteractive-tofile-human
=== RUN   TestRunPreflights/noninteractive-tofile-json
=== RUN   TestRunPreflights/noninteractive-tofile-yaml
--- PASS: TestRunPreflights (11.02s)
    --- PASS: TestRunPreflights/noninteractive-stdout-human (1.85s)
    --- PASS: TestRunPreflights/noninteractive-stdout-json (1.83s)
    --- PASS: TestRunPreflights/noninteractive-stdout-yaml (1.83s)
    --- PASS: TestRunPreflights/noninteractive-tofile-human (1.83s)
    --- PASS: TestRunPreflights/noninteractive-tofile-json (1.83s)
    --- PASS: TestRunPreflights/noninteractive-tofile-yaml (1.83s)
PASS
ok  	github.com/replicatedhq/troubleshoot/pkg/preflight	11.972s
```

File: pkg/preflight/output_to_file.go [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+		if analyzeResult.Strict {
+			result = result + fmt.Sprintf("Strict: %t\n", analyzeResult.Strict)
+		}
+
+		result = result + "\n------------\n"
+
+		results = results + result
+	}
+
+	if err := ioutil.WriteFile(filename, []byte(results), 0644); err != nil {
```
Comment (banjoh) [inline pkg/preflight/output_to_file.go:62]: Use `os.WriteFile`, `ioutil` package is deprecated

**Review by banjoh — APPROVED** [review]
